// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcodAOk_4SbwCOax4c2qJsxPD_K1wpRSI',
    appId: '1:1039026751626:web:23024b0f7c69fa5c744573',
    messagingSenderId: '1039026751626',
    projectId: 'socialapp-ceb53',
    authDomain: 'socialapp-ceb53.firebaseapp.com',
    storageBucket: 'socialapp-ceb53.appspot.com',
    measurementId: 'G-564GPLM3TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-GXXNAtI0agwmnsqMCYKXZAz1s18QZaI',
    appId: '1:1039026751626:android:94827c2fee9c36f3744573',
    messagingSenderId: '1039026751626',
    projectId: 'socialapp-ceb53',
    storageBucket: 'socialapp-ceb53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1OeFZA8k8tNkwSOGRwzp2nFsF77hC4k',
    appId: '1:1039026751626:ios:e65b08ebe6f917a1744573',
    messagingSenderId: '1039026751626',
    projectId: 'socialapp-ceb53',
    storageBucket: 'socialapp-ceb53.appspot.com',
    iosClientId: '1039026751626-v4b726dn3m2ctr1qnbu2oal4l3ku7f0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu1OeFZA8k8tNkwSOGRwzp2nFsF77hC4k',
    appId: '1:1039026751626:ios:e65b08ebe6f917a1744573',
    messagingSenderId: '1039026751626',
    projectId: 'socialapp-ceb53',
    storageBucket: 'socialapp-ceb53.appspot.com',
    iosClientId: '1039026751626-v4b726dn3m2ctr1qnbu2oal4l3ku7f0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
